const test = require('node:test');
const assert = require('node:assert/strict');
const { MappingStore } = require('../src/mappings');
const { classifyProducts } = require('../src/product');
const { GeminiProductClassifier, validateGeminiResults, GEMINI_MODEL } = require('../src/product-classifier');
const { validateUpload, processValidatedUpload } = require('../src/upload');
const { aggregate, applyFilters, csv } = require('../src/reports');
const { classifyStatus } = require('../src/classification');

async function taxonomy(store, client = 'a') { const master = await store.saveMaster(client, 'Beauty & Personal Care'); const product = await store.saveCategory(client, 'Nail Serum', master._id); return { master, product }; }
test('product categories require tenant master categories and remain tenant isolated', async () => { const store = new MappingStore({ mongoUri: null }); await assert.rejects(store.saveCategory('a', 'Nail Serum', null, { requireMaster: true }), { code: 'MASTER_CATEGORY_REQUIRED' }); const { master } = await taxonomy(store); assert.equal((await store.listCategories('a'))[0].masterCategory, master.name); assert.equal((await store.listMasters('b')).length, 0); });
test('known two-level and legacy flat mappings bypass Gemini', async () => { let calls = 0; const provider = { classifyProducts() { calls += 1; } }; const known = await classifyProducts(['S-Famw Nail Serum 349'], { mappings: [{ normalizedValue: 's famw nail serum 349', masterCategory: 'Beauty & Personal Care', productCategory: 'Nail Serum' }], provider }); assert.equal(calls, 0); assert.equal(known.items[0].productCategory, 'Nail Serum'); const legacy = classifyProducts(['Old Product'], { mappings: [{ normalizedValue: 'old product', category: 'Legacy Category' }], provider }); assert.equal(calls, 0); assert.equal(legacy.items[0].masterCategory, null); });
test('unknown products send complete taxonomy and accept specific new categories', async () => { let context; const provider = { classifyProducts(products, value) { context = value; return { model: GEMINI_MODEL, results: [{ product: products[0], masterCategory: 'Beauty & Personal Care', productCategory: 'Nail Serum', confidence: .95 }] }; } }; const result = await classifyProducts(['S-Famw Nail Serum 349'], { masterCategories: [{ name: 'Beauty & Personal Care' }], productCategories: [{ name: 'Face Serum', masterCategory: 'Beauty & Personal Care' }], provider }); assert.deepEqual(context, { masterCategories: ['Beauty & Personal Care'], productCategories: [{ name: 'Face Serum', masterCategory: 'Beauty & Personal Care' }] }); assert.equal(result.items[0].suggestedProductCategory, 'Nail Serum'); });
test('Gemini validation requires safe master and specific product category response', () => { const out = validateGeminiResults({ results: [{ product: 'S-Famw Nail Serum 349', masterCategory: 'Beauty & Personal Care', productCategory: 'Nail Serum' }, { product: 'Bad', masterCategory: '<bad>', productCategory: 'X' }] }, ['S-Famw Nail Serum 349', 'Bad'], { masterCategories: ['Beauty & Personal Care'], productCategories: [] }); assert.equal(out.length, 1); assert.equal(out[0].productCategory, 'Nail Serum'); });
test('approval saves taxonomy/mapping and next upload has zero Gemini calls', async () => { const store = new MappingStore({ mongoUri: null }); const { master } = await taxonomy(store); await store.saveProductMapping('a', 'S-Famw Nail Serum 349', { masterCategory: master._id, productCategory: 'Nail Serum', source: 'AI Approved' }); let calls = 0; const classified = await classifyProducts(['S-Famw Nail Serum 349'], { mappings: await store.list('product', 'a'), provider: { classifyProducts() { calls += 1; } } }); assert.equal(calls, 0); assert.equal(classified.items[0].masterCategory, 'Beauty & Personal Care'); });
test('manual fallback requires both categories and preserves status engine', async () => { const store = new MappingStore({ mongoUri: null }); await assert.rejects(store.saveProductMapping('a', 'Thing', { productCategory: 'Thing' }), { code: 'INVALID_CATEGORY' }); assert.equal(classifyStatus('Ready to Ship').category, 'In Transit'); assert.equal(classifyStatus('RTO NDR').category, 'RTO'); });
test('reports snapshot, filter, and export both taxonomy levels', () => { const rows = [{ normalizedOrderId: '1', category: 'Delivered', originalProductName: 'S-Famw Nail Serum 349', masterCategory: 'Beauty & Personal Care', productCategory: 'Nail Serum', quantity: 1, rowValue: 349 }]; const report = aggregate(rows, 'full'); assert.equal(report.analytics.masterCategory[0].name, 'Beauty & Personal Care'); assert.equal(applyFilters(rows, { masterCategory: 'Beauty & Personal Care' }, 'full').length, 1); assert.match(csv(rows, 'full'), /Master Category/); });
test('upload validation never calls Gemini before processing and processing calls it for unknown products', async () => { let calls = 0; const file = { originalname: 'orders.csv', buffer: Buffer.from('Order ID,Order Date,Status,Product Name,Order Quantity,Product Price,Payment Mode,Courier,Order Source\n1,2026-01-01,Delivered,S-Famw Nail Serum 349,1,10,COD,C,Store\n') }; const validated = validateUpload(file, { classify: false }); assert.equal(validated.success, true); const result = await processValidatedUpload(validated, { productClassifier: { classifyProducts(products) { calls += 1; return { results: [{ product: products[0], masterCategory: 'Beauty & Personal Care', productCategory: 'Nail Serum' }] }; } } }); assert.equal(calls, 1); assert.equal(result.classifications.products[0].mappingSource, 'ai-suggested'); });
test('Gemini uses the hardcoded Flash-Lite model and GEMINI_API_KEY only', () => { const classifier = new GeminiProductClassifier({ apiKey: 'key', model: 'other' }); assert.equal(classifier.model, 'gemini-2.5-flash-lite'); });
