const path = require('node:path');
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const { validateUpload, processValidatedUpload, MAX_FILE_SIZE, csvTemplate, xlsxTemplate } = require('./upload');
const { REPORT_CATEGORIES } = require('./classification');
const { MappingStore } = require('./mappings');
const { ReportStore, ProcessingStore, csv: reportCsv } = require('./reports');
const { GeminiProductClassifier } = require('./product-classifier');

const app = express(); const publicDirectory = path.join(__dirname, '..', 'public'); const mappingStore = new MappingStore(); const reportStore = new ReportStore(); const processingStore = new ProcessingStore();
const clientId = process.env.DEFAULT_CLIENT_ID || 'demo-client';
const productClassifier = new GeminiProductClassifier(); // Server-owned development identity; do not read clientId from requests.
app.disable('x-powered-by');
app.use(helmet({ contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], styleSrc: ["'self'"], scriptSrc: ["'self'"], imgSrc: ["'self'", 'data:'], connectSrc: ["'self'"] } } }));
app.use(cors({ origin: process.env.APP_ORIGIN || false, credentials: true })); app.set('trust proxy', 1); app.use(express.json({ limit: '1mb' })); app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 200, standardHeaders: 'draft-7', legacyHeaders: false }));
const mappingKind = (value) => ['status', 'product'].includes(value) ? value : null;
app.get('/api/health', (request, response) => response.json({ status: 'ok', service: 'deliveryiq', timestamp: new Date().toISOString() }));
app.get('/api/uploads/template/:templateType.:format', (request, response) => { const { templateType, format } = request.params; if (!['simple', 'full'].includes(templateType) || !['csv', 'xlsx'].includes(format)) return response.status(404).json({ error: 'Not found' }); return response.attachment(`deliveryiq-${templateType}-report-template.${format}`).type(format === 'csv' ? 'text/csv' : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(format === 'csv' ? csvTemplate(templateType) : xlsxTemplate(templateType)); });
app.get('/api/uploads/template.csv', (request, response) => response.attachment('deliveryiq-full-report-template.csv').type('text/csv').send(csvTemplate('full')));
app.get('/api/uploads/template.xlsx', (request, response) => response.attachment('deliveryiq-full-report-template.xlsx').type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(xlsxTemplate('full')));
app.get('/api/classifications/config', async (request, response) => { const [masterCategories, productCategories] = await Promise.all([mappingStore.listMasters(clientId), mappingStore.listCategories(clientId)]); return response.json({ statusCategories: REPORT_CATEGORIES, masterCategories, productCategories }); });
app.post('/api/uploads/validate', express.raw({ type: 'application/octet-stream', limit: MAX_FILE_SIZE }), async (request, response) => { const name = request.get('x-file-name'); if (!name) return response.status(400).json({ success: false, code: 'FILE_REQUIRED', message: 'Choose a CSV or XLSX file to validate.', details: {} }); const result = validateUpload({ originalname: name, buffer: request.body }, { classify: false, templateType: request.get('x-template-type') || 'auto' }); if (!result.success) return response.status(result.status).json(result); const active = await processingStore.getActiveProcess(clientId); if (active) return response.status(409).json({ success: false, code: 'ACTIVE_REPORT_PROCESS', message: 'You already have a report in progress. Please finish the current report or remove it before uploading a new file.', process: processingStore.public(active) }); const created = await processingStore.createValidated(clientId, result, request.get('x-report-request-id')); const job = created.job; if (created.existing) return response.status(409).json({ success: false, code: 'ACTIVE_REPORT_PROCESS', message: 'You already have a report in progress. Please finish the current report or remove it before uploading a new file.', process: processingStore.public(job) }); console.info(JSON.stringify({ event: 'report_process_validated', processId: job.processId, productRows: result.summary.productRows, uniqueProducts: result.summary.detectedProducts })); const { normalizedRows, ...safe } = result; return response.json({ ...safe, process: processingStore.public(job) }); });
function finalRowsFromProcess(job) {
  const classifications = job.result?.classifications; if (!classifications) return null;
  const unresolved = [...classifications.statuses, ...classifications.products].some((item) => item.classificationRequired);
  if (unresolved) return null;
  const products = new Map(classifications.products.map((item) => [item.normalizedProductName, item]));
  const statuses = new Map(classifications.statuses.map((item) => [item.value, item]));
  return job.input.normalizedRows.map((source) => { const product = products.get(source.normalizedProductName); const status = statuses.get(source.originalStatus); return { ...source, category: status?.category, normalizedStatus: status?.normalizedStatus, masterCategory: product?.masterCategory, productCategory: product?.productCategory || product?.category, productMappingSource: product?.mappingSource, productClassificationRequired: false }; });
}
async function classifyProcess(job, stage) { console.info(JSON.stringify({ event: 'report_process_classification_started', processId: job.processId })); stage('mapping_statuses'); const [statusMappings, productMappings, masterCategories, productCategories, suggestions] = await Promise.all([mappingStore.list('status', clientId), mappingStore.list('product', clientId), mappingStore.listMasters(clientId), mappingStore.listCategories(clientId), mappingStore.listSuggestions(clientId)]); stage('checking_products'); stage('ai_product_classification'); const result = await processValidatedUpload(job.input, { statusMappings, productMappings, masterCategories, productCategories, suggestions, productClassifier }); const products = result.classifications.products; await mappingStore.saveSuggestions(clientId, products); const unresolved = result.classifications.statuses.some((item) => item.classificationRequired) || products.some((item) => item.classificationRequired); if (unresolved) return result; stage('finalizing_report'); return { result, report: await reportStore.create(clientId, { templateType: result.templateType, sourceFileName: result.file.name, rows: result.normalizedRows, requestId: job.requestId }) }; }
app.get('/api/report-processes/active', async (request, response) => { const job = await processingStore.getActiveProcess(clientId); return response.json({ success: true, process: processingStore.public(job) }); });
app.get('/api/report-processes/:processId', async (request, response) => { const job = await processingStore.get(clientId, request.params.processId); return job ? response.json({ success: true, process: processingStore.public(job) }) : response.status(404).json({ success: false, code: 'PROCESS_NOT_FOUND', message: 'This report process could not be found.' }); });
app.post('/api/report-processes/:processId/start', async (request, response) => { console.info(JSON.stringify({ event: 'report_process_start_requested', processId: request.params.processId })); const job = await processingStore.start(clientId, request.params.processId, classifyProcess); return job ? response.status(202).json({ success: true, process: processingStore.public(job) }) : response.status(404).json({ success: false, code: 'PROCESS_NOT_FOUND', message: 'This report process could not be found.' }); });
app.post('/api/report-processes/:processId/finalize', async (request, response) => { const job = await processingStore.get(clientId, request.params.processId); if (!job) return response.status(404).json({ success: false, code: 'PROCESS_NOT_FOUND', message: 'This report process could not be found.' }); if (job.status === 'completed') return response.json({ success: true, report: job.report, process: processingStore.public(job) }); if (job.status !== 'review_required' && job.status !== 'finalizing') return response.status(409).json({ success: false, code: 'PROCESS_NOT_READY', message: 'Finish processing before finalizing this report.' }); const rows = finalRowsFromProcess(job); if (!rows) return response.status(422).json({ success: false, code: 'CLASSIFICATION_REQUIRED', message: 'Some statuses or products still need classification before generating the report.', process: processingStore.public(job) }); job.status = 'finalizing'; job.stage = 'finalizing_report'; await processingStore.save(job); const report = await reportStore.create(clientId, { templateType: job.input.templateType, sourceFileName: job.input.file.name, rows, requestId: job.requestId }); await processingStore.complete(job, report); return response.status(201).json({ success: true, report, process: processingStore.public(job) }); });
app.get('/api/mappings/:kind', async (request, response) => { const kind = mappingKind(request.params.kind); if (!kind) return response.status(404).json({ error: 'Not found' }); return response.json({ success: true, mappings: await mappingStore.list(kind, clientId) }); });
app.post('/api/report-processes/:processId/review/:kind/:value', async (request, response) => {
  const kind = mappingKind(request.params.kind); const job = await processingStore.get(clientId, request.params.processId);
  if (!kind || !job) return response.status(404).json({ success: false, code: 'PROCESS_NOT_FOUND', message: 'This report process could not be found.' });
  if (job.status !== 'review_required') return response.status(409).json({ success: false, code: 'PROCESS_NOT_READY', message: 'This report is not awaiting review.' });
  try { let update;
    if (kind === 'product') { const action = request.body?.action; if (action === 'reject') { await mappingStore.decideSuggestion(clientId, request.params.value, 'Client Rejected', {}); update = { suggestionStatus: 'Client Rejected', status: 'Client Rejected', classificationRequired: true, manualReason: 'AI suggestion rejected. Please assign a category manually.', suggestedCategory: null, suggestedMasterCategory: null, suggestedProductCategory: null, mappingSource: 'needs-review' }; }
      else { const source = action === 'change' ? 'Client Modified' : action === 'approve' ? 'AI Approved' : 'Manual'; const mapping = await mappingStore.saveProductMapping(clientId, request.params.value, { masterCategory: request.body?.masterCategory, productCategory: request.body?.productCategory, source }); update = { masterCategory: mapping.masterCategory, productCategory: mapping.productCategory, category: mapping.productCategory, mappingSource: source, suggestionStatus: source, status: source, classificationRequired: false, manualReason: null }; await mappingStore.decideSuggestion(clientId, request.params.value, source, update); }
    } else { const mapping = await mappingStore.save('status', clientId, request.params.value, request.body?.category); update = { category: mapping.category, status: 'Client Modified', classificationRequired: false }; }
    const saved = await processingStore.updateReview(clientId, job.processId, kind, request.params.value, update); if (!saved) return response.status(404).json({ success: false, code: 'REVIEW_ITEM_NOT_FOUND', message: 'This review item could not be found.' }); return response.json({ success: true, process: processingStore.public(saved) });
  } catch (error) { return response.status(422).json({ success: false, code: error.code || 'INVALID_MAPPING', message: 'Select a valid category before saving.' }); }
});
app.delete('/api/report-processes/:processId', async (request, response) => { const job = await processingStore.cancel(clientId, request.params.processId); return job ? response.json({ success: true, process: processingStore.public(job) }) : response.status(404).json({ success: false, code: 'PROCESS_NOT_FOUND', message: 'This report process could not be removed.' }); });
app.post('/api/mappings/:kind', async (request, response) => { const kind = mappingKind(request.params.kind); if (!kind) return response.status(404).json({ error: 'Not found' }); const value = kind === 'status' ? request.body?.status : request.body?.product; if (!String(value ?? '').trim()) return response.status(422).json({ success: false, code: 'INVALID_MAPPING', message: 'Choose a valid value to map.' }); try { const source = ['AI Approved', 'Client Modified', 'Manual'].includes(request.body?.source) ? request.body.source : (kind === 'product' ? 'Manual' : null); const mapping = kind === 'product' ? await mappingStore.saveProductMapping(clientId, value, { masterCategory: request.body?.masterCategory, productCategory: request.body?.productCategory, source }) : await mappingStore.save(kind, clientId, value, request.body?.category, { source }); return response.json({ success: true, mapping }); } catch (error) { return response.status(422).json({ success: false, code: error.code || 'INVALID_MAPPING', message: 'Select a valid master category and product category.' }); } });
app.delete('/api/mappings/:kind/:value', async (request, response) => { const kind = mappingKind(request.params.kind); if (!kind) return response.status(404).json({ error: 'Not found' }); return response.json({ success: true, removed: await mappingStore.remove(kind, clientId, request.params.value) }); });
app.get('/api/product-categories', async (request, response) => response.json({ success: true, categories: await mappingStore.listCategories(clientId, true) }));
app.get('/api/master-categories', async (request, response) => response.json({ success: true, categories: await mappingStore.listMasters(clientId, true) }));
app.post('/api/master-categories', async (request, response) => { try { return response.status(201).json({ success: true, category: await mappingStore.saveMaster(clientId, request.body?.name) }); } catch (error) { return response.status(422).json({ success: false, code: error.code, message: 'Enter a unique master category name of up to 80 characters.' }); } });
app.patch('/api/master-categories/:name', async (request, response) => { try { const category = await mappingStore.renameMaster(clientId, request.params.name, request.body?.name); return category ? response.json({ success: true, category }) : response.status(404).json({ error: 'Not found' }); } catch (error) { return response.status(422).json({ success: false, code: error.code, message: 'Enter a unique master category name.' }); } });
app.patch('/api/master-categories/:name/active', async (request, response) => { const category = await mappingStore.setMasterActive(clientId, request.params.name, request.body?.active); return category ? response.json({ success: true, category }) : response.status(404).json({ error: 'Not found' }); });
app.post('/api/product-categories', async (request, response) => { try { return response.status(201).json({ success: true, category: await mappingStore.saveCategory(clientId, request.body?.name, request.body?.masterCategoryId || request.body?.masterCategory, { requireMaster: true }) }); } catch (error) { return response.status(422).json({ success: false, code: error.code || 'INVALID_CATEGORY', message: error.code === 'MASTER_CATEGORY_REQUIRED' ? 'A valid master category is required.' : 'Enter a unique product category name of up to 80 characters.' }); } });
app.patch('/api/product-categories/:name', async (request, response) => { try { const category = await mappingStore.renameCategory(clientId, request.params.name, request.body?.name); return category ? response.json({ success: true, category }) : response.status(404).json({ error: 'Not found' }); } catch (error) { return response.status(422).json({ success: false, code: error.code || 'INVALID_CATEGORY', message: error.code === 'CATEGORY_EXISTS' ? 'A product category with that name already exists.' : 'Enter a valid category name.' }); } });
app.patch('/api/product-classification-suggestions/:product', async (request, response) => { try { const suggestion = await mappingStore.decideSuggestion(clientId, request.params.product, request.body?.status, request.body || {}); return response.json({ success: true, suggestion }); } catch (error) { return response.status(422).json({ success: false, code: error.code || 'INVALID_SUGGESTION', message: 'We could not save that review decision. Please try again.' }); } });
app.patch('/api/product-categories/:name/active', async (request, response) => { const category = await mappingStore.setCategoryActive(clientId, request.params.name, request.body?.active); return category ? response.json({ success: true, category }) : response.status(404).json({ error: 'Not found' }); });
app.post('/api/reports', express.raw({ type: 'application/octet-stream', limit: MAX_FILE_SIZE }), async (request, response) => { const name = request.get('x-file-name'); const templateType = request.get('x-template-type'); if (!name) return response.status(400).json({ success: false, code: 'FILE_REQUIRED', message: 'Choose a CSV or XLSX file to generate a report.' }); const [statusMappings, productMappings] = await Promise.all([mappingStore.list('status', clientId), mappingStore.list('product', clientId)]); const result = await validateUpload({ originalname: name, buffer: request.body }, { statusMappings, productMappings, templateType }); if (!result.success) return response.status(result.status).json(result); const unresolved = result.classifications.statuses.filter((item) => item.classificationRequired).length + result.classifications.products.filter((item) => item.classificationRequired).length; if (unresolved) return response.status(422).json({ success: false, code: 'CLASSIFICATION_REQUIRED', message: 'Some statuses or products still need classification before generating the report.', details: { unresolved } }); try { const report = await reportStore.create(clientId, { templateType, sourceFileName: result.file.name, rows: result.normalizedRows, requestId: request.get('x-report-request-id') || undefined }); return response.status(201).json({ success: true, report }); } catch { return response.status(500).json({ success: false, code: 'REPORT_SAVE_FAILED', message: 'We could not save this report. Please try again.' }); } });
app.get('/api/reports', async (request, response) => response.json({ success: true, reports: await reportStore.list(clientId) }));
app.get('/api/reports/:reportId', async (request, response) => { const { export: output, ...filters } = request.query; const detail = await reportStore.detail(clientId, request.params.reportId, filters); if (!detail) return response.status(404).json({ error: 'Not found' }); if (output === 'csv') return response.attachment('deliveryiq-report-export.csv').type('text/csv').send(reportCsv(detail.exportRows, detail.templateType)); delete detail.exportRows; return response.json({ success: true, report: detail }); });
app.use((error, request, response, next) => error?.type === 'entity.too.large' ? response.status(413).json({ success: false, code: 'FILE_TOO_LARGE', message: 'The uploaded file is larger than the 10 MB file limit.', details: { maxBytes: MAX_FILE_SIZE } }) : next(error)); app.use(express.static(publicDirectory)); app.use('/api', (request, response) => response.status(404).json({ error: 'Not found' })); app.get('*', (request, response) => response.sendFile(path.join(publicDirectory, 'index.html')));
module.exports = app;
