const path = require('node:path');
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const { rateLimit } = require('express-rate-limit');
const { loadEnvironment } = require('./utils');
const { MAX_FILE_SIZE, csvTemplate, validateUpload, xlsxTemplate } = require('./upload');
const { REPORT_CATEGORIES } = require('./classification');
const { MappingStore } = require('./mappings');
const { ReportStore, csv: reportCsv } = require('./reports');
loadEnvironment();
const app = express(); const publicDirectory = path.join(__dirname, '..', 'public'); const mappingStore = new MappingStore(); const reportStore = new ReportStore();
// This is deliberately server-owned demo scope until authentication supplies identity.
const clientId = process.env.DEFAULT_CLIENT_ID || 'demo-client';
const productCategories = (process.env.PRODUCT_CATEGORIES || 'Clothing,Drinkware,Electronics,Personal Care').split(',').map((value) => value.trim()).filter(Boolean);
app.disable('x-powered-by'); app.use(helmet({ contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], styleSrc: ["'self'"], scriptSrc: ["'self'"], imgSrc: ["'self'", 'data:'], connectSrc: ["'self'"] } } })); app.use(cors({ origin: process.env.APP_ORIGIN || false, credentials: true })); app.set('trust proxy', 1); app.use(express.json({ limit: '1mb' })); app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 200, standardHeaders: 'draft-7', legacyHeaders: false }));
app.get('/api/health', (request, response) => response.json({ status: 'ok', service: 'deliveryiq', timestamp: new Date().toISOString() }));
app.get('/api/uploads/template/:templateType.:format', (request, response) => { const { templateType, format } = request.params; if (!['simple', 'full'].includes(templateType) || !['csv', 'xlsx'].includes(format)) return response.status(404).json({ error: 'Not found' }); return response.attachment(`deliveryiq-${templateType}-report-template.${format}`).type(format === 'csv' ? 'text/csv' : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(format === 'csv' ? csvTemplate(templateType) : xlsxTemplate(templateType)); });
// Legacy full-template links remain valid.
app.get('/api/uploads/template.csv', (request, response) => response.attachment('deliveryiq-full-report-template.csv').type('text/csv').send(csvTemplate('full')));
app.get('/api/uploads/template.xlsx', (request, response) => response.attachment('deliveryiq-full-report-template.xlsx').type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(xlsxTemplate('full')));
app.post('/api/uploads/validate', express.raw({ type: 'application/octet-stream', limit: MAX_FILE_SIZE }), async (request, response) => { const name = request.get('x-file-name'); if (!name) return response.status(400).json({ success: false, code: 'FILE_REQUIRED', message: 'Choose a CSV or XLSX file to validate.', details: {} }); const [statusMappings, productMappings] = await Promise.all([mappingStore.list('status', clientId), mappingStore.list('product', clientId)]); const result = await validateUpload({ originalname: name, buffer: request.body }, { statusMappings, productMappings, templateType: request.get('x-template-type') || 'auto' }); return response.status(result.success ? 200 : result.status).json(result); });
app.get('/api/classifications/config', (request, response) => response.json({ statusCategories: REPORT_CATEGORIES, productCategories }));
app.post('/api/mappings/:kind', async (request, response) => { const kind = request.params.kind; if (!['status', 'product'].includes(kind)) return response.status(404).json({ error: 'Not found' }); const value = kind === 'status' ? request.body?.status : request.body?.product; if ((kind === 'status' && !REPORT_CATEGORIES.includes(request.body?.category)) || !String(value ?? '').trim() || !String(request.body?.category ?? '').trim()) return response.status(422).json({ success: false, code: 'INVALID_MAPPING', message: 'Choose a valid category and a value to map.' }); try { return response.json({ success: true, mapping: await mappingStore.save(kind, clientId, value, request.body.category) }); } catch (error) { return response.status(422).json({ success: false, code: error.code || 'INVALID_MAPPING', message: 'We could not save that mapping. Please try again.' }); } });
app.post('/api/reports', express.raw({ type: 'application/octet-stream', limit: MAX_FILE_SIZE }), async (request, response) => { const name = request.get('x-file-name'); const templateType = request.get('x-template-type'); if (!name) return response.status(400).json({ success: false, code: 'FILE_REQUIRED', message: 'Choose a CSV or XLSX file to generate a report.' }); const [statusMappings, productMappings] = await Promise.all([mappingStore.list('status', clientId), mappingStore.list('product', clientId)]); const result = await validateUpload({ originalname: name, buffer: request.body }, { statusMappings, productMappings, templateType }); if (!result.success) return response.status(result.status).json(result); const unresolved = result.classifications.statuses.filter((item) => item.classificationRequired).length + result.classifications.products.filter((item) => item.classificationRequired).length; if (unresolved) return response.status(422).json({ success: false, code: 'CLASSIFICATION_REQUIRED', message: 'Some statuses or products still need classification before generating the report.', details: { unresolved } }); try { const report = await reportStore.create(clientId, { templateType, sourceFileName: result.file.name, rows: result.normalizedRows, requestId: request.get('x-report-request-id') || undefined }); return response.status(201).json({ success: true, report }); } catch { return response.status(500).json({ success: false, code: 'REPORT_SAVE_FAILED', message: 'We could not save this report. Please try again.' }); } });
app.get('/api/reports', async (request, response) => response.json({ success: true, reports: await reportStore.list(clientId) }));
app.get('/api/reports/:reportId', async (request, response) => { const { export: output, ...filters } = request.query; const detail = await reportStore.detail(clientId, request.params.reportId, filters); if (!detail) return response.status(404).json({ error: 'Not found' }); if (output === 'csv') return response.attachment('deliveryiq-report-export.csv').type('text/csv').send(reportCsv(detail.exportRows, detail.templateType)); delete detail.exportRows; return response.json({ success: true, report: detail }); });
app.use((error, request, response, next) => error?.type === 'entity.too.large' ? response.status(413).json({ success: false, code: 'FILE_TOO_LARGE', message: 'The uploaded file is larger than the 10 MB file limit.', details: { maxBytes: MAX_FILE_SIZE } }) : next(error)); app.use(express.static(publicDirectory)); app.use('/api', (request, response) => response.status(404).json({ error: 'Not found' })); app.get('*', (request, response) => response.sendFile(path.join(publicDirectory, 'index.html')));
module.exports = app;
