const REPORT_CATEGORIES = Object.freeze(['Delivered', 'In Transit', 'NDR', 'RTO', 'Cancelled', 'Other']);
const UNMAPPED = 'UNMAPPED';

function normalizeMappingValue(value) {
  return String(value ?? '')
    .normalize('NFKC')
    .trim()
    .toLowerCase()
    .replace(/[‐‑‒–—―_-]+/g, ' ')
    .replace(/[\\/]+/g, ' ')
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizedSet(values) { return new Set(values.map(normalizeMappingValue)); }
const rules = {
  rto: normalizedSet(['RTO', 'RTO Initiated', 'RTO Initiate', 'RTO Raised', 'RTO Requested', 'RTO Request', 'RTO Started', 'RTO Processing', 'RTO In Progress', 'RTO Pending', 'RTO Confirmed', 'Return to Origin', 'Returned to Origin', 'Returning to Origin', 'Return Initiated', 'Return Started', 'RTO In Transit', 'RTO IT', 'Return In Transit', 'Return to Origin In Transit', 'Returning to Origin In Transit', 'RTO OFD', 'RTO Out for Delivery', 'Return Out for Delivery', 'Return to Origin Out for Delivery', 'RTO Delivered', 'RTO Delivery', 'RTO Returned', 'RTO Completed', 'RTO Received', 'Returned to Seller', 'Returned to Warehouse', 'RTO NDR', 'RTO NDR Raised', 'RTO Delivery Failed', 'RTO Reattempt', 'RTO Acknowledged', 'RTO Rejected', 'RTO Disposed', 'Disposed', 'Disposed Of', 'Return Disposed', 'Reached RTO', 'Reached Origin', 'Reached at Origin', 'RAO', 'Return Received at Origin', 'Return Reached Origin']),
  ndr: normalizedSet(['NDR', 'NDR Raised', 'NDR Generated', 'NDR Created', 'NDR Initiated', 'NDR Pending', 'NDR Open', 'NDR Case', 'NDR Attempt', 'NDR Reason', 'Non Delivery', 'Non Delivery Report', 'Undelivered', 'Shipment Undelivered', 'Order Undelivered', 'Delivery Undelivered', 'Delivery Failed', 'Delivery Failure', 'Failed Delivery', 'Delivery Attempt Failed', 'Delivery Attempt Unsuccessful', 'Delivery Unsuccessful', 'Attempted Delivery', 'Delivery Attempted', 'Unable to Deliver', 'Could Not Deliver', 'Not Delivered', 'Customer Not Available', 'Customer Unavailable', 'Consignee Not Available', 'Consignee Unavailable', 'Recipient Not Available', 'Recipient Unavailable', 'Customer Unreachable', 'Recipient Unreachable', 'Consignee Unreachable', 'Phone Unreachable', 'Phone Switched Off', 'No Response', 'Not Reachable', 'Customer Refused', 'Customer Rejected', 'Consignee Refused', 'Consignee Rejected', 'Recipient Refused', 'Recipient Rejected', 'Refused To Accept', 'Refused Delivery', 'Address Issue', 'Address Incorrect', 'Incorrect Address', 'Wrong Address', 'Incomplete Address', 'Address Incomplete', 'Address Not Found', 'Wrong Pincode', 'Incorrect Pincode', 'Pincode Issue', 'PIN Code Issue', 'Door Locked', 'House Locked', 'Office Closed', 'Shop Closed', 'Premises Closed', 'COD Refused', 'COD Rejected', 'COD Payment Failed', 'Cash Not Available', 'Delivery Exception', 'Delivery Attempt Exception', 'Delivery Issue', 'Reattempt', 'Reattempt Requested', 'Delivery Reattempt', 'NDR Reattempt']),
  delivered: normalizedSet(['Delivered', 'Delivery Completed', 'Delivery Complete', 'Successfully Delivered', 'Delivered Successfully', 'Shipment Delivered', 'Order Delivered', 'Shipment Delivery Completed', 'Delivery Successful', 'Successfully Delivered to Customer', 'Delivered to Customer', 'Delivered to Consignee', 'Delivered to Recipient', 'Received by Customer', 'Received by Recipient', 'Customer Received', 'POD', 'POD Generated', 'POD Uploaded', 'Proof of Delivery', 'Delivery Confirmed', 'Complete', 'Completed', 'DLVD']),
  cancelled: normalizedSet(['Cancelled', 'Canceled', 'Cancellation', 'Cancel', 'Order Cancelled', 'Order Canceled', 'Cancelled Order', 'Canceled Order', 'Shipment Cancelled', 'Shipment Canceled', 'Cancelled Shipment', 'Canceled Shipment', 'Cancelled by Customer', 'Canceled by Customer', 'Customer Cancelled', 'Customer Canceled', 'Cancelled by Seller', 'Canceled by Seller', 'Seller Cancelled', 'Seller Canceled', 'Cancelled by Merchant', 'Canceled by Merchant', 'Merchant Cancelled', 'Merchant Canceled', 'Courier Cancelled', 'Courier Canceled', 'Cancelled Before Pickup', 'Cancelled Before Shipment', 'Cancelled Before Dispatch', 'AWB Cancelled', 'AWB Canceled', 'Shipment Cancellation', 'Order Cancellation']),
  transit: normalizedSet(['Ready to Ship', 'RTS', 'Ready for Dispatch', 'Ready for Pickup', 'Ready To Pickup', 'Pickup Scheduled', 'Scheduled Pickup', 'Pickup Requested', 'Pickup Queued', 'Pickup Assigned', 'Pickup Rescheduled', 'Out for Pickup', 'OFP', 'Picked Up', 'Shipment Picked Up', 'Order Picked Up', 'Pickup Completed', 'Pickup Done', 'PUD', 'PKD', 'Shipped', 'Shipment Shipped', 'Order Shipped', 'Dispatched', 'Shipment Dispatched', 'Dispatched Shipment', 'Forward Shipment', 'In Transit', 'Transit', 'IT', 'Shipment In Transit', 'Shipment Transit', 'Moving', 'In Movement', 'On the Way', 'On Its Way', 'En Route', 'Enroute', 'At Origin Hub', 'Origin Hub', 'Origin Facility', 'Reached Origin Hub', 'Departed Origin Hub', 'At Hub', 'Hub In', 'Hub Out', 'Reached Hub', 'Arrived at Hub', 'Departed Hub', 'Bag In', 'Bag Out', 'Bagged', 'Bag Received', 'Bag Dispatched', 'Reached Destination Hub', 'Reached at Destination Hub', 'Destination Hub', 'Destination Hub Received', 'RAD', 'Out for Delivery', 'OFD', 'Shipment Out for Delivery', 'Order Out for Delivery', 'Delayed', 'Shipment Delayed', 'Delivery Delayed', 'Misrouted', 'Misroute', 'Shipment Misrouted', 'Misrouted Shipment', 'Wrong Hub', 'Sent to Wrong Hub', 'Routing Error', 'Rerouted', 'Shipment Rerouted', 'Shipment Re Routed']),
  other: normalizedSet(['Lost', 'Shipment Lost', 'Lost Shipment', 'Damaged', 'Shipment Damaged', 'Damaged Shipment', 'Destroyed', 'Shipment Destroyed', 'On Hold', 'Hold', 'Shipment On Hold', 'Shipment Hold', 'Hold at Hub', 'Exception', 'Shipment Exception', 'Technical Exception', 'Technical Issue', 'System Exception', 'Invalid AWB', 'AWB Error', 'Invalid Shipment', 'Shipment Error', 'Manifest Error', 'Weight Discrepancy', 'Weight Issue', 'Dispute', 'Dispute Raised', 'Dispute Accepted', 'Dispute Rejected', 'Investigation', 'Under Investigation', 'Fraud', 'Fraud Suspected', 'Shipment Blocked', 'Blocked Shipment', 'Booking Failed', 'Shipment Booking Failed', 'AWB Generation Failed'])
};

function mappingIndex(mappings = []) { return new Map(mappings.map((mapping) => [mapping.normalizedValue || mapping.normalizedStatus || mapping.normalizedProduct, mapping.category])); }
function result(originalStatus, normalizedStatus, category, mappingSource) { return { originalStatus, normalizedStatus, category: category === UNMAPPED ? null : category, mappingSource, classificationRequired: category === UNMAPPED }; }
function classifyStatus(originalStatus, clientMappings = []) {
  const normalizedStatus = normalizeMappingValue(originalStatus); const saved = mappingIndex(clientMappings).get(normalizedStatus);
  if (REPORT_CATEGORIES.includes(saved)) return result(originalStatus, normalizedStatus, saved, 'client');
  for (const [rule, category] of [['rto', 'RTO'], ['ndr', 'NDR'], ['delivered', 'Delivered'], ['cancelled', 'Cancelled'], ['transit', 'In Transit'], ['other', 'Other']]) if (rules[rule].has(normalizedStatus)) return result(originalStatus, normalizedStatus, category, 'generic');
  return result(originalStatus, normalizedStatus, UNMAPPED, 'unmapped');
}
function classifyProduct(originalProduct, clientMappings = [], genericMappings = []) {
  const normalizedProduct = normalizeMappingValue(originalProduct); const category = mappingIndex(clientMappings).get(normalizedProduct) || mappingIndex(genericMappings).get(normalizedProduct);
  return { originalProduct, normalizedProduct, category: category || null, mappingSource: category ? (mappingIndex(clientMappings).has(normalizedProduct) ? 'client' : 'generic') : 'unmapped', classificationRequired: !category };
}
function isReportCategory(category) { return REPORT_CATEGORIES.includes(category); }
module.exports = { REPORT_CATEGORIES, UNMAPPED, classifyProduct, classifyStatus, isReportCategory, normalizeMappingValue };
