const mongoose = require('mongoose');
const { isReportCategory, normalizeMappingValue } = require('./classification');
const { normalizeCategory } = require('./product');

const mappingSchema = new mongoose.Schema({ clientId: { type: String, required: true }, normalizedValue: { type: String, required: true }, originalExample: { type: String, required: true }, category: String, productCategory: String, productCategoryId: mongoose.Schema.Types.ObjectId, masterCategory: String, masterCategoryId: mongoose.Schema.Types.ObjectId, source: { type: String, default: null }, updatedBy: { type: String, default: 'system' }, previousCategory: String, previousProductCategory: String, previousMasterCategory: String }, { timestamps: true, versionKey: false });
mappingSchema.index({ clientId: 1, normalizedValue: 1 }, { unique: true });
const masterSchema = new mongoose.Schema({ clientId: { type: String, required: true }, name: { type: String, required: true }, normalizedName: { type: String, required: true }, active: { type: Boolean, default: true }, updatedBy: { type: String, default: 'system' } }, { timestamps: true, versionKey: false });
masterSchema.index({ clientId: 1, normalizedName: 1 }, { unique: true });
// masterCategoryId is intentionally optional at schema level so existing flat records remain readable.
const categorySchema = new mongoose.Schema({ clientId: { type: String, required: true }, name: { type: String, required: true }, normalizedName: { type: String, required: true }, masterCategoryId: mongoose.Schema.Types.ObjectId, active: { type: Boolean, default: true }, updatedBy: { type: String, default: 'system' } }, { timestamps: true, versionKey: false });
categorySchema.index({ clientId: 1, masterCategoryId: 1, normalizedName: 1 }, { unique: true, sparse: true });
const StatusMapping = mongoose.models.StatusMapping || mongoose.model('StatusMapping', mappingSchema, 'statusMappings');
const ProductMapping = mongoose.models.ProductMapping || mongoose.model('ProductMapping', mappingSchema, 'productMappings');
const MasterCategory = mongoose.models.MasterCategory || mongoose.model('MasterCategory', masterSchema, 'masterCategories');
const ProductCategory = mongoose.models.ProductCategory || mongoose.model('ProductCategory', categorySchema, 'productCategories');
const suggestionSchema = new mongoose.Schema({ clientId: { type: String, required: true }, normalizedProductName: { type: String, required: true }, originalProductName: { type: String, required: true }, suggestedCategory: String, suggestedProductCategory: String, suggestedMasterCategory: String, confidence: Number, reason: String, model: String, status: { type: String, required: true }, finalCategory: String, finalProductCategory: String, finalMasterCategory: String, decidedAt: Date }, { timestamps: true, versionKey: false });
suggestionSchema.index({ clientId: 1, normalizedProductName: 1, createdAt: -1 });
const ProductClassificationSuggestion = mongoose.models.ProductClassificationSuggestion || mongoose.model('ProductClassificationSuggestion', suggestionSchema, 'productClassificationSuggestions');
const duplicate = (code) => Object.assign(new Error(code), { code });

class MappingStore {
  constructor({ mongoUri = process.env.MONGODB_URI } = {}) { this.mongoUri = mongoUri; this.memory = { status: new Map(), product: new Map(), master: new Map(), category: new Map(), suggestion: new Map() }; this.connection = null; }
  async database() { if (!this.mongoUri || this.mongoUri.includes('127.0.0.1:27017/deliveryiq2026') && process.env.NODE_ENV === 'test') return null; if (!this.connection) this.connection = mongoose.connect(this.mongoUri, { serverSelectionTimeoutMS: 1500 }).catch(() => null); return this.connection; }
  async list(kind, clientId) { const Model = kind === 'status' ? StatusMapping : ProductMapping; if (await this.database()) return Model.find({ clientId }).sort({ updatedAt: -1 }).lean(); return [...(this.memory[kind].get(clientId)?.values() || [])].sort((a, b) => b.updatedAt - a.updatedAt); }
  async listMasters(clientId, inactive = false) { if (await this.database()) return MasterCategory.find({ clientId, ...(inactive ? {} : { active: true }) }).sort({ name: 1 }).lean(); return [...(this.memory.master.get(clientId)?.values() || [])].filter((x) => inactive || x.active).sort((a, b) => a.name.localeCompare(b.name)); }
  async saveMaster(clientId, name, options = {}) { const value = normalizeCategory(name); if (!clientId || !value) throw duplicate('INVALID_MASTER_CATEGORY'); const normalizedName = normalizeMappingValue(value); const record = { clientId, name: value, normalizedName, active: options.active !== false, updatedBy: options.updatedBy || 'client' }; if (await this.database()) { if (await MasterCategory.exists({ clientId, normalizedName })) throw duplicate('MASTER_CATEGORY_EXISTS'); try { return (await MasterCategory.create(record)).toObject(); } catch (e) { if (e.code === 11000) throw duplicate('MASTER_CATEGORY_EXISTS'); throw e; } } const values = this.memory.master.get(clientId) || new Map(); if (values.has(normalizedName)) throw duplicate('MASTER_CATEGORY_EXISTS'); const saved = { ...record, _id: `master-${normalizedName}`, createdAt: new Date(), updatedAt: new Date() }; values.set(normalizedName, saved); this.memory.master.set(clientId, values); return saved; }
  async master(clientId, idOrName) { const name = normalizeMappingValue(idOrName); const all = await this.listMasters(clientId, true); return all.find((x) => String(x._id) === String(idOrName) || x.normalizedName === name) || null; }
  async setMasterActive(clientId, idOrName, active) { const master = await this.master(clientId, idOrName); if (!master) return null; if (await this.database()) return MasterCategory.findByIdAndUpdate(master._id, { active: Boolean(active), updatedBy: 'client' }, { new: true }).lean(); master.active = Boolean(active); master.updatedAt = new Date(); return master; }
  async renameMaster(clientId, idOrName, name) { const master = await this.master(clientId, idOrName); const next = normalizeCategory(name); if (!master) return null; if (!next) throw duplicate('INVALID_MASTER_CATEGORY'); const existing = await this.master(clientId, next); if (existing && String(existing._id) !== String(master._id)) throw duplicate('MASTER_CATEGORY_EXISTS'); if (await this.database()) return MasterCategory.findByIdAndUpdate(master._id, { name: next, normalizedName: normalizeMappingValue(next), updatedBy: 'client' }, { new: true }).lean(); master.name = next; master.normalizedName = normalizeMappingValue(next); return master; }
  async save(kind, clientId, originalExample, category, options = {}) {
    if (kind === 'product' && options.masterCategory) return this.saveProductMapping(clientId, originalExample, { productCategory: category, masterCategory: options.masterCategory, source: options.source, updatedBy: options.updatedBy });
    if (kind === 'product') { const normalizedValue = normalizeMappingValue(originalExample); const update = { clientId, normalizedValue, originalExample: String(originalExample).trim(), category: normalizeCategory(category), productCategory: normalizeCategory(category), source: options.source || 'Manual', updatedBy: options.updatedBy || 'client' }; const values = this.memory.product.get(clientId) || new Map(); const saved = { ...values.get(normalizedValue), ...update, createdAt: values.get(normalizedValue)?.createdAt || new Date(), updatedAt: new Date() }; values.set(normalizedValue, saved); this.memory.product.set(clientId, values); return saved; }
    if (!isReportCategory(category)) throw duplicate('INVALID_CATEGORY'); const normalizedValue = normalizeMappingValue(originalExample); if (!clientId || !normalizedValue) throw duplicate('INVALID_MAPPING');
    const update = { clientId, normalizedValue, originalExample: String(originalExample).trim(), category, source: options.source || null, updatedBy: options.updatedBy || 'client' }; if (await this.database()) return StatusMapping.findOneAndUpdate({ clientId, normalizedValue }, update, { upsert: true, new: true }).lean(); const values = this.memory.status.get(clientId) || new Map(); const saved = { ...values.get(normalizedValue), ...update, createdAt: values.get(normalizedValue)?.createdAt || new Date(), updatedAt: new Date() }; values.set(normalizedValue, saved); this.memory.status.set(clientId, values); return saved;
  }
  async saveProductMapping(clientId, originalExample, { productCategory, masterCategory, source, updatedBy } = {}) {
    const product = normalizeCategory(productCategory); if (!clientId || !normalizeMappingValue(originalExample) || !product) throw duplicate('INVALID_MAPPING');
    const category = await this.category(clientId, product, masterCategory); if (!category) throw duplicate('INVALID_CATEGORY');
    const master = await this.master(clientId, category.masterCategoryId); if (!master) throw duplicate('MASTER_CATEGORY_REQUIRED');
    const normalizedValue = normalizeMappingValue(originalExample); const update = { clientId, normalizedValue, originalExample: String(originalExample).trim(), category: category.name, productCategory: category.name, productCategoryId: category._id, masterCategory: master.name, masterCategoryId: master._id, updatedBy: updatedBy || 'client' };
    const sourceFor = (previous) => previous?.source === 'AI Approved' && previous.productCategory !== category.name ? 'Client Modified' : (source || previous?.source || 'Manual');
    if (await this.database()) { const previous = await ProductMapping.findOne({ clientId, normalizedValue }).lean(); return ProductMapping.findOneAndUpdate({ clientId, normalizedValue }, { ...update, source: sourceFor(previous), ...(previous?.productCategory !== category.name ? { previousCategory: previous?.category, previousProductCategory: previous?.productCategory, previousMasterCategory: previous?.masterCategory } : {}) }, { upsert: true, new: true }).lean(); }
    const values = this.memory.product.get(clientId) || new Map(); const previous = values.get(normalizedValue); const saved = { ...previous, ...update, source: sourceFor(previous), createdAt: previous?.createdAt || new Date(), updatedAt: new Date() }; values.set(normalizedValue, saved); this.memory.product.set(clientId, values); return saved;
  }
  async listCategories(clientId, includeInactive = false) { const masters = await this.listMasters(clientId, true); const byId = new Map(masters.map((m) => [String(m._id), m])); const decorate = (x) => ({ ...x, masterCategory: byId.get(String(x.masterCategoryId))?.name || null }); if (await this.database()) return (await ProductCategory.find({ clientId, ...(includeInactive ? {} : { active: true }) }).sort({ name: 1 }).lean()).map(decorate); return [...(this.memory.category.get(clientId)?.values() || [])].filter((x) => includeInactive || x.active).map(decorate).sort((a, b) => a.name.localeCompare(b.name)); }
  async category(clientId, name, masterIdOrName) { const key = normalizeMappingValue(name); const categories = await this.listCategories(clientId, true); return categories.find((x) => x.normalizedName === key && (!masterIdOrName || String(x.masterCategoryId) === String(masterIdOrName) || normalizeMappingValue(x.masterCategory) === normalizeMappingValue(masterIdOrName))) || null; }
  async saveCategory(clientId, name, masterCategory, options = {}) { const value = normalizeCategory(name); const master = await this.master(clientId, masterCategory); if (!value) throw duplicate('INVALID_CATEGORY'); const normalizedName = normalizeMappingValue(value); if (!master) { if (options.requireMaster) throw duplicate('MASTER_CATEGORY_REQUIRED'); const values = this.memory.category.get(clientId) || new Map(); if (values.has(`legacy:${normalizedName}`)) throw duplicate('CATEGORY_EXISTS'); const saved = { clientId, name: value, normalizedName, active: true, _id: `legacy-${normalizedName}`, createdAt: new Date(), updatedAt: new Date() }; values.set(`legacy:${normalizedName}`, saved); this.memory.category.set(clientId, values); return saved; } const record = { clientId, name: value, normalizedName, masterCategoryId: master._id, active: options.active !== false, updatedBy: options.updatedBy || 'client' }; if (await this.database()) { if (await ProductCategory.exists({ clientId, masterCategoryId: master._id, normalizedName })) throw duplicate('CATEGORY_EXISTS'); try { return { ...(await ProductCategory.create(record)).toObject(), masterCategory: master.name }; } catch (e) { if (e.code === 11000) throw duplicate('CATEGORY_EXISTS'); throw e; } } const values = this.memory.category.get(clientId) || new Map(); const key = `${master._id}:${normalizedName}`; if (values.has(key)) throw duplicate('CATEGORY_EXISTS'); const saved = { ...record, _id: `category-${key}`, createdAt: new Date(), updatedAt: new Date(), masterCategory: master.name }; values.set(key, saved); this.memory.category.set(clientId, values); return saved; }
  async remove(kind, clientId, value) { const key = normalizeMappingValue(value); const Model = kind === 'status' ? StatusMapping : ProductMapping; if (await this.database()) return Boolean((await Model.deleteOne({ clientId, normalizedValue: key })).deletedCount); return this.memory[kind].get(clientId)?.delete(key) || false; }
  async setCategoryActive(clientId, name, active, masterCategory) { const category = await this.category(clientId, name, masterCategory); if (!category) return null; if (await this.database()) return ProductCategory.findByIdAndUpdate(category._id, { active: Boolean(active), updatedBy: 'client' }, { new: true }).lean(); category.active = Boolean(active); category.updatedAt = new Date(); return category; }
  async renameCategory(clientId, oldName, name, masterCategory) { const category = await this.category(clientId, oldName, masterCategory); const next = normalizeCategory(name); if (!category) return null; if (!next) throw duplicate('INVALID_CATEGORY'); const existing = await this.category(clientId, next, category.masterCategoryId); if (existing && String(existing._id) !== String(category._id)) throw duplicate('CATEGORY_EXISTS'); if (await this.database()) { await ProductCategory.findByIdAndUpdate(category._id, { name: next, normalizedName: normalizeMappingValue(next), updatedBy: 'client' }); await ProductMapping.updateMany({ clientId, productCategoryId: category._id }, { productCategory: next, category: next, previousProductCategory: category.name }); return { ...category, name: next, normalizedName: normalizeMappingValue(next) }; } category.name = next; category.normalizedName = normalizeMappingValue(next); for (const map of this.memory.product.get(clientId)?.values() || []) if (String(map.productCategoryId) === String(category._id)) { map.category = next; map.productCategory = next; } return category; }
  async saveSuggestions(clientId, products) { const records = products.filter((x) => x.mappingSource === 'ai-suggested' || x.mappingSource === 'needs-review').map((x) => ({ clientId, normalizedProductName: x.normalizedProductName, originalProductName: x.originalProductName, suggestedCategory: x.suggestedProductCategory || null, suggestedProductCategory: x.suggestedProductCategory || null, suggestedMasterCategory: x.suggestedMasterCategory || null, confidence: x.confidence ?? null, reason: x.suggestionReason || null, model: x.model || null, status: x.suggestionStatus || 'Needs Review' })); if (await this.database()) return Promise.all(records.map((x) => ProductClassificationSuggestion.findOneAndUpdate({ clientId, normalizedProductName: x.normalizedProductName }, { $setOnInsert: x }, { upsert: true, new: true }).lean())); const values = this.memory.suggestion.get(clientId) || []; records.forEach((x) => { if (!values.some((v) => v.normalizedProductName === x.normalizedProductName)) values.push({ ...x, createdAt: new Date(), updatedAt: new Date() }); }); this.memory.suggestion.set(clientId, values); return records; }
  async listSuggestions(clientId) { if (await this.database()) return ProductClassificationSuggestion.aggregate([{ $match: { clientId } }, { $sort: { createdAt: -1 } }, { $group: { _id: '$normalizedProductName', item: { $first: '$$ROOT' } } }, { $replaceRoot: { newRoot: '$item' } }]); return this.memory.suggestion.get(clientId) || []; }
  async decideSuggestion(clientId, product, status, details = {}) { const key = normalizeMappingValue(product); if (!key || !['Client Rejected', 'AI Approved', 'Client Modified', 'Manual'].includes(status)) throw duplicate('INVALID_SUGGESTION'); const update = { status, finalCategory: details.productCategory || details.finalCategory || null, finalProductCategory: details.productCategory || details.finalCategory || null, finalMasterCategory: details.masterCategory || null, decidedAt: new Date() }; if (await this.database()) return ProductClassificationSuggestion.findOneAndUpdate({ clientId, normalizedProductName: key }, update, { sort: { createdAt: -1 }, new: true }).lean(); const x = (this.memory.suggestion.get(clientId) || []).find((i) => i.normalizedProductName === key); return x && Object.assign(x, update);
  }
}
module.exports = { MappingStore, MasterCategory, ProductCategory, ProductMapping };
