const mongoose = require('mongoose');
const { isReportCategory, normalizeMappingValue } = require('./classification');
const { normalizeCategory } = require('./product');

const mappingSchema = new mongoose.Schema({
  clientId: { type: String, required: true }, normalizedValue: { type: String, required: true }, originalExample: { type: String, required: true },
  category: { type: String, required: true }, source: { type: String, default: null }, updatedBy: { type: String, default: 'system' }, previousCategory: String
}, { timestamps: true, versionKey: false });
mappingSchema.index({ clientId: 1, normalizedValue: 1 }, { unique: true });
mappingSchema.index({ clientId: 1, category: 1 });
const categorySchema = new mongoose.Schema({ clientId: { type: String, required: true }, name: { type: String, required: true }, normalizedName: { type: String, required: true }, active: { type: Boolean, default: true }, updatedBy: { type: String, default: 'system' } }, { timestamps: true, versionKey: false });
categorySchema.index({ clientId: 1, normalizedName: 1 }, { unique: true });
const StatusMapping = mongoose.models.StatusMapping || mongoose.model('StatusMapping', mappingSchema, 'statusMappings');
const ProductMapping = mongoose.models.ProductMapping || mongoose.model('ProductMapping', mappingSchema, 'productMappings');
const suggestionSchema = new mongoose.Schema({ clientId: { type: String, required: true }, normalizedProductName: { type: String, required: true }, originalProductName: { type: String, required: true }, suggestedCategory: String, confidence: Number, reason: String, model: String, status: { type: String, required: true }, finalCategory: String, decidedAt: Date }, { timestamps: true, versionKey: false });
suggestionSchema.index({ clientId: 1, normalizedProductName: 1, createdAt: -1 });
const ProductCategory = mongoose.models.ProductCategory || mongoose.model('ProductCategory', categorySchema, 'productCategories');
const ProductClassificationSuggestion = mongoose.models.ProductClassificationSuggestion || mongoose.model('ProductClassificationSuggestion', suggestionSchema, 'productClassificationSuggestions');

class MappingStore {
  constructor({ mongoUri = process.env.MONGODB_URI } = {}) { this.mongoUri = mongoUri; this.memory = { status: new Map(), product: new Map(), category: new Map(), suggestion: new Map() }; this.connection = null; }
  async database() { if (!this.mongoUri || this.mongoUri.includes('127.0.0.1:27017/deliveryiq2026') && process.env.NODE_ENV === 'test') return null; if (!this.connection) this.connection = mongoose.connect(this.mongoUri, { serverSelectionTimeoutMS: 1500 }).catch(() => null); return this.connection; }
  async list(kind, clientId) { const Model = kind === 'status' ? StatusMapping : ProductMapping; if (await this.database()) return Model.find({ clientId }).sort({ updatedAt: -1 }).lean(); return [...(this.memory[kind].get(clientId)?.values() || [])].sort((a, b) => b.updatedAt - a.updatedAt); }
  async save(kind, clientId, originalExample, category, options = {}) {
    const finalCategory = kind === 'product' ? normalizeCategory(category) : category;
    if ((kind === 'status' && !isReportCategory(finalCategory)) || (kind === 'product' && !finalCategory)) { const error = new Error('INVALID_CATEGORY'); error.code = 'INVALID_CATEGORY'; throw error; }
    const normalizedValue = normalizeMappingValue(originalExample); if (!clientId || !normalizedValue) { const error = new Error('INVALID_MAPPING'); error.code = 'INVALID_MAPPING'; throw error; }
    const Model = kind === 'status' ? StatusMapping : ProductMapping;
    const sourceFor = (previous) => kind !== 'product' ? (options.source || null) : (previous?.source === 'AI Approved' && previous.category !== finalCategory ? 'Client Modified' : (options.source || previous?.source || 'Manual'));
    if (await this.database()) { const previous = await Model.findOne({ clientId, normalizedValue }).lean(); const update = { clientId, normalizedValue, originalExample: String(originalExample).trim(), category: finalCategory, source: sourceFor(previous), updatedBy: options.updatedBy || 'client' }; return Model.findOneAndUpdate({ clientId, normalizedValue }, { ...update, ...(previous?.category !== finalCategory ? { previousCategory: previous?.category } : {}) }, { upsert: true, new: true, setDefaultsOnInsert: true }).lean(); }
    const values = this.memory[kind].get(clientId) || new Map(); const previous = values.get(normalizedValue); const update = { clientId, normalizedValue, originalExample: String(originalExample).trim(), category: finalCategory, source: sourceFor(previous), updatedBy: options.updatedBy || 'client' }; const record = { ...previous, ...update, ...(previous?.category !== finalCategory ? { previousCategory: previous?.category } : {}), createdAt: previous?.createdAt || new Date(), updatedAt: new Date() }; values.set(normalizedValue, record); this.memory[kind].set(clientId, values); return record;
  }
  async saveSuggestions(clientId, products) { const suggestions = products.filter((item) => item.mappingSource === 'ai-suggested' || item.mappingSource === 'needs-review').map((item) => ({ clientId, normalizedProductName: item.normalizedProductName, originalProductName: item.originalProductName, suggestedCategory: item.suggestedCategory || null, confidence: item.confidence ?? null, reason: item.suggestionReason || null, model: item.model || null, status: item.suggestionStatus || 'Needs Review' })); if (!suggestions.length) return []; if (await this.database()) return ProductClassificationSuggestion.insertMany(suggestions); const values = this.memory.suggestion.get(clientId) || []; const records = suggestions.map((item) => ({ ...item, createdAt: new Date(), updatedAt: new Date() })); values.push(...records); this.memory.suggestion.set(clientId, values); return records; }
  async decideSuggestion(clientId, product, status, finalCategory = null) { const normalizedProductName = normalizeMappingValue(product); if (!normalizedProductName || !['Client Rejected', 'AI Approved', 'Client Modified', 'Manual'].includes(status)) throw Object.assign(new Error('INVALID_SUGGESTION'), { code: 'INVALID_SUGGESTION' }); const update = { status, finalCategory, decidedAt: new Date() }; if (await this.database()) return ProductClassificationSuggestion.findOneAndUpdate({ clientId, normalizedProductName }, update, { sort: { createdAt: -1 }, new: true }).lean(); const values = this.memory.suggestion.get(clientId) || []; const suggestion = [...values].reverse().find((item) => item.normalizedProductName === normalizedProductName); if (!suggestion) return null; Object.assign(suggestion, update, { updatedAt: new Date() }); return suggestion; }
  async remove(kind, clientId, normalizedValue) { const key = normalizeMappingValue(normalizedValue); const Model = kind === 'status' ? StatusMapping : ProductMapping; if (await this.database()) return Boolean((await Model.deleteOne({ clientId, normalizedValue: key })).deletedCount); return (this.memory[kind].get(clientId)?.delete(key)) || false; }
  async listCategories(clientId, includeInactive = false) { if (await this.database()) return ProductCategory.find({ clientId, ...(includeInactive ? {} : { active: true }) }).sort({ name: 1 }).lean(); return [...(this.memory.category.get(clientId)?.values() || [])].filter((item) => includeInactive || item.active).sort((a, b) => a.name.localeCompare(b.name)); }
  async saveCategory(clientId, name, options = {}) { const value = normalizeCategory(name); if (!clientId || !value) { const error = new Error('INVALID_CATEGORY'); error.code = 'INVALID_CATEGORY'; throw error; } const normalizedName = normalizeMappingValue(value); const update = { clientId, name: value, normalizedName, active: options.active !== false, updatedBy: options.updatedBy || 'client' }; if (await this.database()) return ProductCategory.findOneAndUpdate({ clientId, normalizedName }, update, { upsert: true, new: true, setDefaultsOnInsert: true }).lean(); const values = this.memory.category.get(clientId) || new Map(); const previous = values.get(normalizedName); const record = { ...previous, ...update, createdAt: previous?.createdAt || new Date(), updatedAt: new Date() }; values.set(normalizedName, record); this.memory.category.set(clientId, values); return record; }
  async setCategoryActive(clientId, name, active) { const key = normalizeMappingValue(name); if (await this.database()) { const category = await ProductCategory.findOneAndUpdate({ clientId, normalizedName: key }, { active: Boolean(active), updatedBy: 'client' }, { new: true }).lean(); return category; } const category = this.memory.category.get(clientId)?.get(key); if (!category) return null; category.active = Boolean(active); category.updatedAt = new Date(); return category; }
  async renameCategory(clientId, oldName, name) { const oldKey = normalizeMappingValue(oldName); const next = normalizeCategory(name); const nextKey = normalizeMappingValue(next); if (!next) throw Object.assign(new Error('INVALID_CATEGORY'), { code: 'INVALID_CATEGORY' }); if (await this.database()) { const category = await ProductCategory.findOne({ clientId, normalizedName: oldKey }); if (!category) return null; if (oldKey !== nextKey && await ProductCategory.exists({ clientId, normalizedName: nextKey })) throw Object.assign(new Error('CATEGORY_EXISTS'), { code: 'CATEGORY_EXISTS' }); category.name = next; category.normalizedName = nextKey; try { await category.save(); } catch (error) { if (error?.code === 11000) throw Object.assign(new Error('CATEGORY_EXISTS'), { code: 'CATEGORY_EXISTS' }); throw error; } await ProductMapping.updateMany({ clientId, category: oldName }, { category: next, previousCategory: oldName, updatedAt: new Date() }); return category.toObject(); } const values = this.memory.category.get(clientId); const category = values?.get(oldKey); if (!category) return null; if (oldKey !== nextKey && values.has(nextKey)) throw Object.assign(new Error('CATEGORY_EXISTS'), { code: 'CATEGORY_EXISTS' }); values.delete(oldKey); const updated = { ...category, name: next, normalizedName: nextKey, updatedAt: new Date() }; values.set(updated.normalizedName, updated); for (const mapping of this.memory.product.get(clientId)?.values() || []) if (mapping.category === oldName) { mapping.previousCategory = oldName; mapping.category = next; mapping.updatedAt = new Date(); } return updated; }
}
module.exports = { MappingStore };
