const { normalizeMappingValue } = require('./classification');
function normalizeProductName(value) { return normalizeMappingValue(value); }
function normalizeCategory(value) { const text = String(value || '').trim().replace(/\s+/g, ' '); return text ? text.slice(0, 80) : null; }
function validAiCategory(value) { const text = normalizeCategory(value); return text && !/[\u0000-\u001f\u007f<>]/.test(text) ? text : null; }
function taxonomy(categories = [], masters = []) { const masterNames = masters.map((x) => typeof x === 'string' ? x : x.name).filter(Boolean); const products = categories.map((x) => typeof x === 'string' ? { name: x, masterCategory: null } : x).filter((x) => x.name); return { masterCategories: masterNames, productCategories: products }; }
function classifyProducts(products, { mappings = [], categories = [], masterCategories = [], productCategories, suggestions = [], provider } = {}) {
  const unique = new Map(); for (const value of products) { const originalProductName = String(value || '').trim(); const normalizedProductName = normalizeProductName(originalProductName); if (!normalizedProductName) continue; const item = unique.get(normalizedProductName) || { value: originalProductName, originalProductName, normalizedProductName, count: 0 }; item.count += 1; unique.set(normalizedProductName, item); }
  const saved = new Map(mappings.map((m) => [m.normalizedValue || m.normalizedProductName, m])); const items = [...unique.values()].map((item) => { const mapping = saved.get(item.normalizedProductName); const productCategory = normalizeCategory(mapping?.productCategory || mapping?.category); const masterCategory = normalizeCategory(mapping?.masterCategory); return { ...item, category: productCategory, productCategory, masterCategory, confidence: productCategory ? 1 : null, mappingSource: productCategory ? 'client' : 'unmapped', classificationRequired: !productCategory }; });
  const prior = new Map(suggestions.map((x) => [x.normalizedProductName, x])); const unknown = items.filter((x) => x.classificationRequired); const pending = unknown.filter((x) => !prior.has(x.normalizedProductName));
  for (const item of unknown.filter((x) => prior.has(x.normalizedProductName))) { const s = prior.get(item.normalizedProductName); const pc = validAiCategory(s.suggestedProductCategory || s.suggestedCategory); const mc = validAiCategory(s.suggestedMasterCategory); if (s.status === 'AI Suggested' && pc && mc) Object.assign(item, { suggestedCategory: pc, suggestedProductCategory: pc, suggestedMasterCategory: mc, confidence: s.confidence ?? null, suggestionReason: s.reason || null, mappingSource: 'ai-suggested', classificationRequired: true, suggestionStatus: 'AI Suggested', model: s.model || null }); else Object.assign(item, { mappingSource: 'needs-review', classificationRequired: true, suggestionStatus: s.status, manualReason: 'AI could not confidently classify this product. Please assign categories manually.' }); }
  if (!provider || !pending.length) return { providerUnavailable: false, items };
  const current = taxonomy(productCategories || categories, masterCategories); const apply = (response) => { const responseByProduct = new Map((response.results || []).map((x) => [x.product, x])); for (const item of pending) { const s = responseByProduct.get(item.originalProductName); const productCategory = validAiCategory(s?.productCategory || s?.category); const masterCategory = validAiCategory(s?.masterCategory); if (productCategory && masterCategory && productCategory !== 'NO_MATCH') Object.assign(item, { suggestedCategory: productCategory, suggestedProductCategory: productCategory, suggestedMasterCategory: masterCategory, confidence: s.confidence ?? null, suggestionReason: s.reason || null, mappingSource: 'ai-suggested', classificationRequired: true, suggestionStatus: 'AI Suggested', model: response.model }); else Object.assign(item, { mappingSource: 'needs-review', suggestionStatus: 'Needs Review', classificationRequired: true, manualReason: 'AI could not confidently classify this product. Please assign categories manually.', model: response.model }); } return { providerUnavailable: Boolean(response.providerUnavailable), providerError: response.providerError || null, items }; };
  const response = provider.classifyProducts(pending.map((x) => x.originalProductName), current); return response?.then ? response.then(apply) : apply(response);
}
module.exports = { normalizeProductName, normalizeCategory, validAiCategory, classifyProducts };
